### ISSUE TITLE
exercise data sets

### ISSUE THREAD

**Issue by mdbeckman** [jbpost2/TeachingWithR#1]
should they be hosted at https://www4.stat.ncsu.edu/~online/datasets/  or linked to the repo?

**Comment by jbpost2** [comment]
If you have an easy way (with a nice-ish looking link) to pull from github that's fine.  If not, let's put in on that web.  Let me know.

**Comment by mdbeckman** [comment]
https://jbpost2.github.io/TeachingWithR/datasets/BabyNamesSupp.csv

^ that's what it will look like.  I think that's pretty reasonable, so I'll go with it
