### ISSUE TITLE
Repo webpage?

### ISSUE THREAD

**Issue by mdbeckman** [jbpost2/TeachingWithR#2]
do we have a webpage for the Repo so we can deploy exercise documents & solutions sequentially (vs sharing one big one)

**Comment by jbpost2** [comment]
I was going to use the github pages functionality and just use that.  Does that work for you?

**Comment by mdbeckman** [comment]
Got it!  I wasn't able to see the the Settings page to find the URL, but I guessed it :)  I'm in good shape now
