### ISSUE TITLE
how to best deploy exercises to participants during workshop?

### ISSUE THREAD

**Issue by mdbeckman** [jbpost2/TeachingWithR#4]
I've embedded URLs  in the slides for the exercises after each segment of the workshop.  That only works if people can get to the slides easily (not so much if they're watching on screen).  

What do you think is the best way to get these to people at the right time?  We could add a section to the landing page for the repo (i.e., README) with links to both exercise & solution pages.  Then we just need to share the link for the main page and they can get to everything they need.  

Thoughts?

**Comment by mdbeckman** [comment]
p.s. this isn't really "assigned" to you, I just wanted to make sure it would push an email.  I can do it, but wanted to let you make the call

**Comment by jbpost2** [comment]
Just about done with what I am trying for this.  Check here for the format and let me know what you think:
https://jbpost2.github.io/TeachingWithR/CourseFiles.html

**Comment by jbpost2** [comment]
Also, I put a button the main page to go to the course files page.

**Comment by mdbeckman** [comment]
That really looks great, how can I help?  Do you imagine the exercise & resource sections to appear as a list, or do you have something more fancy in mind?

**Comment by jbpost2** [comment]
?  Not sure.  I just added in the links to other courses in the learning resources section.  

I don't know the best way to add in the stuff for the exercises.  Probably just a list for now - if there is time I can go in and fancy-it-up.  Do you mind adding that stuff?

Also, I'm going to read through those exercises this afternoon at some point and I'll let you know if I see any typos or anything.  Almost there!!

**Comment by mdbeckman** [comment]
Sounds great!  Also, now that we have some data about the audience, let me know if you think we need to cut exercises from any of the parts.

**Comment by mdbeckman** [comment]
Should I link to both Rmd & html?  (Just one or the other?)  

I was initially thinking that providing html would make sense so people would be creating their own Rmd document, but maybe I should provide both Rmd & html for the solution docs?

**Comment by jbpost2** [comment]
Looks good with both links like you have it now.

**Comment by mdbeckman** [comment]
oops, messed up the commit message, that was supposed to close the issue
